[[constraint]]
  name = "github.com/gochain-io/gochain"
  version = "^2.1.61"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "^0.8.0"

[prune]
  go-tests = true
  unused-packages = true
  [[prune.project]]
    name = "github.com/gochain-io/gochain"
    go-tests = true
    non-go = false
    unused-packages = false
